name: Next.js Application CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm test || echo "No tests available"

  build:
    needs: test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload Next.js build artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-build-${{ matrix.os }}
          path: .next/
          compression-level: 9
          retention-days: 7

      - name: Upload public directory
        uses: actions/upload-artifact@v4
        with:
          name: public-dir-${{ matrix.os }}
          path: public/
          compression-level: 9
          retention-days: 7

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: next-build-ubuntu-latest
          path: .next
          
      - name: Download public directory
        uses: actions/download-artifact@v4
        with:
          name: public-dir-ubuntu-latest
          path: public
          
      - name: Deploy to production
        run: npm run deploy
  
